[features]
seeds = false
[programs.localnet]
solana_twitter = "6gaU2ExKZ7P7xrW7vqPhFrdPGVjM2HV831acJtJgRxH"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/rohit/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
